#cloud-config

coreos:
  etcd2:
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    advertise-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    initial-cluster: master=http://10.222.1.1:2380
    proxy: on
  fleet:
    metadata: role=node
  units:
    - name: fleet.service
      command: start
    - name: flanneld.service
      command: start
      drop-ins:
        - name: 50-network-config.conf
          content: |
            [Unit]
            Requires=etcd2.service
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{"Network": "10.244.0.0/16", "Backend": {"Type": "vxlan"}}'
    - name: iptables-restore.service
      enable: true
      command: start

    - name: docker.service
      command: start
      drop-ins:
        - name: 50-insecure-registry.conf
          content: |
            [Unit]
            Requires=flanneld.service
            After=flanneld.service
            [Service]
            Environment=DOCKER_OPTS='--insecure-registry="0.0.0.0/0"'
write_files:
  - path: /var/lib/iptables/rules-save
    permissions: 0644
    owner: 'root:root'
    content: |
      *filter
      :INPUT DROP [0:0]
      :FORWARD DROP [0:0]
      :OUTPUT ACCEPT [0:0]
      -A INPUT -i lo -j ACCEPT
      -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      # -A INPUT -p tcp -s 10.140.0.0/25 -m tcp --dport 22 -j ACCEPT
      # -A INPUT -p tcp -s 10.222.1.0/25 -m tcp --dport 22 -j ACCEPT
      # -A INPUT -p tcp -s 10.244.0.0/16 -m tcp --dport 22 -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 2379 -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 4001 -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 2380 -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 7001 -j ACCEPT

      -A INPUT -p tcp -m tcp --dport 8081 -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 9042 -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 7000 -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 9160 -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 7199 -j ACCEPT
      -A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
      -A INPUT -p icmp -m icmp --icmp-type 3 -j ACCEPT
      -A INPUT -p icmp -m icmp --icmp-type 11 -j ACCEPT
      COMMIT
